### ISSUE TITLE
Armor Broken

### ISSUE THREAD

**Issue by JupiterYourHero** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#12]
https://gyazo.com/55cc11f3db091362dab383756aa9e6bd

**Comment by TheXFactor117** [comment]
Known issue - I'm looking into it (I think Armor reductions still calculate properly but there is a slight chance that Armor reductions don't work).

I'm going to re-work the vanilla Armor system in Alpha 7, which will fix these issues.

**Comment by TheXFactor117** [comment]
@Feltarkh200 That makes perfect sense - I'm actually most likely going to implement our own armor reduction system, foregoing the vanilla system entirely so this won't be an issue under that.

If I revert back to the vanilla armor system in the future, this will be fixed by using a new UUID per armor piece.

**Comment by TheXFactor117** [comment]
This should be fixed in the next update.
