### ISSUE TITLE
Mobs become unkillable at over 1024.0 health when MaxHealth per mob is set to a high value in the config

### ISSUE THREAD

**Issue by DuNamarSundavar** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#20]
As explained in the title, if the MaxHealth of mobs in the config file is set to a high value and one is fighting mobs in an area with a high enough mob/area level, the mob's health caps at 1,024.0 and the mob becomes unkillable (its health drops to 0.0 and remains there).

**Comment by TheXFactor117** [comment]
Minecraft limits the maximum health of entities to be 1024 due to synchronization purposes from server to client. I thought I read somewhere that this was changed and that limit didn't exist anymore, but I must have been wrong.

As a result, enemies over 1024 health probably will bug out. I'll need to do some behind the scenes scaling and trickery for monsters to have "over" 1024 health and scale damage accordingly. I'll work on this now and will push out a hotfix when I get this and a few other issues ironed out (most likely in 0.6.1.3 - I'll update this issue when it is fixed and which version it will be officially fixed for).

**Comment by TheXFactor117** [comment]
Should be fixed in the next update ;)
