### ISSUE TITLE
[Suggestion] Compact with Scaling Health Difficulty

### ISSUE THREAD

**Issue by SeriousCreeper** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#7]
Heya,

currently the area difficulty scales depending on how far away you are from spawn. That works fine if people like to settle near spawn, but if you want to wander a bit first to find a biome to stay in, it's gonna make mobs quite difficult. 

The scaling health mod has a different modes for scaling difficulty, one of them being over time. It also can mix peoples personal difficulty level together to create an average difficulty in a specific area. 

Would it be possible to get a compact with that mod so that the mobs in Loot/Conquer use the scaling health difficulty level as well? 

Cheers,
SC

**Comment by TheXFactor117** [comment]
It could be possible to add some kind of manual integration with the mod. The only issue with that is a LOT of stuff revolve around LSC's Area Level - monsters spawn depending on the level, loot is calculated on the level, even structures will eventually spawn depending on the level. Depending on how Scaling Health's levels work, it could be possible.

I'm just trying to think through how players are supposed to progress in LSC down the road and whether or not it would be compatible with that kind of scaling/leveling. If you make everything dependent on the player's level (e.g. the average difficulty in Scaling Health), if you play in SP, or if you are relatively alone in MP, the monsters will scale with you which would create a sense that the player isn't actually becoming any stronger (they'll never be able to go back and kill Level 1 monsters with ease).

I think the better option would be to add different options for how LSC's Area Level is calculated. I added a config option to allow the user to define how many chunks are needed for the Area Level to go up. For now, I'll probably not do anything, though it is something I wanted to tweak in the future (I had also thought about doing what Hack/Mine did in having Biomes become an Area and leveling it that way).

**Comment by SeriousCreeper** [comment]
I see what you mean. Right now in LSC, the only way to get higher level mobs, is to travel to a higher level area. Your player level does not scale up mob levels around you right? 

Going back to easier areas and feel stronger is definitely nice. At the same time, if you dont travel much, enemies will become really easy and remove any sort of challenge i think. 

But perhaps it's just what you prefer. With scaling health, in one of the modes, difficulty increases over time, which kinda forces you to become stronger (through better gear and such). You don't ever really become over powered (if configured correctly) and stay challenged all the time. 

So i'm thinking, if someone would want to use the scaling health difficulty with LSC, they wouldn't want to become stronger and go back killing low level enemies. If that's what they wanted to do, they'd either not use scaling health or turn that difficulty scaling off, i think. 

But having a different scaling system inside LSC itself would be nice too i think. I suggested something similar to Scaling Health as well, but having support for GameStages for example could be nice. Basically have the area difficulty always the same value, but let it scale through gamestages (or commands). So if a player makes progress, the world overall. But i guess that wouldn't work well in multiplayer then, hm... yeah that would only work well if the area difficulty depends on the players level/progress, instead of the world spawn.

**Comment by TheXFactor117** [comment]
I think you make some pretty good points in that LSC's Area Leveling system is very linear and not very flexible, which could pose some problems in terms of customization and flexibility. I'll definitely go back to the drawing board on this one and see if I can create a customizable progression system. Integration with GameStages/Scaling Health is definitely possible, though integration isn't something I want to focus on at this point in time - I'm more focused on fixing issues, balancing, and adding in more of the "base" content LSC will add.

In terms of what might happen with the system, I think we'll have to come up with a solution to the problem. Because it's so early in development, I'm having a hard time coming up with something that'll work considering I don't know exactly how the development will unfold - for example, I've thought about adding a Level cap of 50 for players (Monster's level cap would be higher, if not uncapped). In addition to that, players wouldn't stop leveling after 50, but there would be additional leveling/progression systems (e.g. prestiges or something similar). And all of this needs to work with the Area Leveling system to provide some sort of balance/progression as well as outlining where structures are supposed to spawn (for example, I was thinking about making the Corrupted Tower only spawn in a range of Area Levels, though that idea could be scrapped completely).

I think, for now, there's not much I can do. In later Alpha versions or perhaps the first few Beta versions, I'll definitely have an idea of how it needs to be implemented. Again, the Alpha stage of the mod is primarily built for basic balancing/bug fixing in addition to implementing the core features of the mod (I'm eventually going to work on Abilities and underground Dungeons for example in later Alphas).

**Comment by TheXFactor117** [comment]
Closing this for now - a re-work of the leveling system will most likely happen eventually.

**Comment by SeriousCreeper** [comment]
Woops didn't see your last reply. Makes all sense, and you seem to have some exciting ideas. Looking forward to how it develops and glad you are open to revisit this at one point!
